[tool.poetry]
name = "preppy"
version = "0.1.0"
description = "Python package to preprocess data"
authors = ["Chimaobi Amadi <maobiamadi@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
